### ISSUE TITLE
Milestone Report 2 - A summary of work done by each team member

### ISSUE THREAD

**Issue by emirhansarac29** [bounswe/bounswe2019group1#103]
Check the list below when your work is done:
- [ ]  Eray Kurtuluş
- [ ] Ömer Faruk Doğru
- [ ] Mehmet Altay İnce 
- [x] Emirhan Saraç
- [x] İrem Üstünboyacıoğlu
- [ ] Ufuk Yılmaz
- [x] Mete Kurt
- [ ] Ömer Toptaş
- [ ] İlker Özkan

**Comment by metekurt** [comment]
Done

**Comment by irem-ustunboyacioglu** [comment]
Done
