### ISSUE TITLE
Create Pull Request Template

### ISSUE THREAD

**Issue by ufukyilmaz** [bounswe/bounswe2019group1#132]
Create a default pull request template for our project repository. 
[Details](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository)
You can look at [these pull request templates](https://github.com/devspace/awesome-github-templates)

**Comment by ufukyilmaz** [comment]
https://github.com/bounswe/bounswe2019group1/pull/130

**Comment by ycerend** [comment]
Pull request template has been created for android, backend and frontend seperately.
