### ISSUE TITLE
Fav Repos

### ISSUE THREAD

**Issue by altayince** [bounswe/bounswe2019group1#3]
Edit "Favourite Repositories" in our wiki page. I created a template and added mine but feel free to change it.
Check the list below when your work is done:
- [x]  Eray Kurtuluş
- [x] Ömer Faruk Doğru
- [x] Mehmet Altay İnce 
- [x] Emirhan Saraç
- [x] İrem Üstünboyacıoğlu
- [x] Ufuk Yılmaz
- [x] Mete Kurt
- [x] Ömer Toptaş
- [ ] İlker Özkan
- [x] Emre Hoşer

**Comment by dogruomerfaruk** [comment]
Done

**Comment by metekurt** [comment]
Done
