### ISSUE TITLE
Review the Feedback for Assignment 3 

### ISSUE THREAD

**Issue by irem-ustunboyacioglu** [bounswe/bounswe2019group1#30]
Review the feedback for assignment 3 and add necessary changes. Deadline: 13.03.2019 @ 18.00

**Comment by metekurt** [comment]
Some modifications were done for search mechanism at the mockup according to the feedback.

**Comment by altayince** [comment]
Some modifications were done for Megean scneario according to the feedback

**Comment by irem-ustunboyacioglu** [comment]
Some modifications were done for Atılgan Scenario according to the feedback (1st and 2nd comment).

**Comment by emirhansarac29** [comment]
Mockup 2 related modifications are done related to feedbacks
