### ISSUE TITLE
Edit the Diagrams according to Feedback

### ISSUE THREAD

**Issue by metekurt** [bounswe/bounswe2019group1#33]

**Comment by uskudarli** [comment]
There is so much detail that can be provided here that makes performing the task as well as reviewing them when completed. For example the review comments.

Also, you should create separate issues for to assign to specific people who are responsible for specific diagrams. This way it is clear who is assigned to edit (or review) what.

As such there should be numerous issues that correspond to work being done by team members.

**Comment by irem-ustunboyacioglu** [comment]
New issues have been created according to the comment.
