### ISSUE TITLE
Edit the Class Diagram according to Feedback for Diagrams.

### ISSUE THREAD

**Issue by irem-ustunboyacioglu** [bounswe/bounswe2019group1#34]

**Comment by irem-ustunboyacioglu** [comment]
feedback #6 
Missing input parameters were added to methods in Basic User, Portfolio, Event Controller and Article Controller classes.

**Comment by emirhansarac29** [comment]
feedback #9 handled

feedback #8 handled
Location class type is changed to gmaps, refers to google map api.
The reason why we are using location in Event class is that we will use locations to give a better responses on customers, more clearly we want users to be aware of close events with respect to distance.

feedback #7 handled
In class diagram, Investment class has stopLimit and lossLimit. stopLimit refers to upper limit, and stopLimit refers to lower limit.

**Comment by emirhansarac29** [comment]
feedback #6 remaining small number of parameters added
