### ISSUE TITLE
Review the Class Diagram

### ISSUE THREAD

**Issue by irem-ustunboyacioglu** [bounswe/bounswe2019group1#38]
Review the Class Diagram to see whether it is compatible with other diagrams.

**Comment by emirhansarac29** [comment]
feedback #9 handled

**Comment by emirhansarac29** [comment]
feedback #10 handled
Location class type is changed to gmaps, refers to google map api.
The reason why we are using location in Event class is that we will use locations to give a better responses on customers, more clearly we want users to be aware of close events with respect to distance.

**Comment by emirhansarac29** [comment]
feedback #7 handled
In class diagram, Investment class has stopLimit and lossLimit. stopLimit refers to upper limit, and stopLimit refers to lower limit.

**Comment by omertoptas** [comment]
I think you have covered everything needed in this class diagram except annotations. I can't see anything about annotations in this class diagram. Shouldn't the class diagram include something about annotations ?

**Comment by ufukyilmaz** [comment]
I think we need to add a user interface class to our diagram to manage views.

**Comment by ufukyilmaz** [comment]
> I think we need to add a user interface class to our diagram to manage views.

or add view functions to controllers to do this functionality.
