### ISSUE TITLE
Add your personal page on wiki

### ISSUE THREAD

**Issue by altayince** [bounswe/bounswe2019group1#4]
Add your personal page on wiki:
Check the list below when your work is done:
- [x]  Eray Kurtuluş
- [x] Ömer Faruk Doğru
- [x] Mehmet Altay İnce 
- [x] Emirhan Saraç
- [x] İrem Üstünboyacıoğlu
- [x] Ufuk Yılmaz
- [x] Mete Kurt
- [x] Ömer Toptaş
- [x] İlker Özkan
- [x] Emre Hoşer

**Comment by emirhansarac29** [comment]
Done

**Comment by ufukyilmaz** [comment]
Done

**Comment by metekurt** [comment]
Done
