### ISSUE TITLE
Milestone Report 1 - A summary of work done by each team member

### ISSUE THREAD

**Issue by emirhansarac29** [bounswe/bounswe2019group1#41]
Check the list below when your work is done:
- [x]  Eray Kurtuluş
- [x] Ömer Faruk Doğru
- [x] Mehmet Altay İnce 
- [x] Emirhan Saraç
- [x] İrem Üstünboyacıoğlu
- [x] Ufuk Yılmaz
- [x] Mete Kurt
- [x] Ömer Toptaş
- [x] İlker Özkan
- [ ] Emre Hoşer

**Comment by metekurt** [comment]
Done.

**Comment by omertoptas** [comment]
Completed.

**Comment by ufukyilmaz** [comment]
Done

**Comment by dogruomerfaruk** [comment]
I am done.

**Comment by ilkerozkan1** [comment]
Done
