### ISSUE TITLE
Create a User Story for Milestone Demo(Web)

### ISSUE THREAD

**Issue by ufukyilmaz** [bounswe/bounswe2019group1#509]
Create a user story that demonstrates the features we added from last milestone to this time.
Features implemented:
- Text and Image Annotations
- Transaction Logic(Wallet Page, Equipment Page etc.)
- Events Page
...more

**Comment by metekurt** [comment]
Done. 
Please check the [link](https://github.com/bounswe/bounswe2019group1/wiki/User-Scenarios-451-(F))
