### ISSUE TITLE
Studying an API that will be useful for our project

### ISSUE THREAD

**Issue by irem-ustunboyacioglu** [bounswe/bounswe2019group1#66]
Search for APIs and choose which ones can be useful for the project. _Deadline: 21.04.2019 - 23.59_

**Comment by irem-ustunboyacioglu** [comment]
This [list of public APIs](https://github.com/toddmotto/public-apis) on github is very inspirational.  It is a wide-ranging list including many different functionalities on different areas. We can check them to find an appropriate API. The ones under Cryptocurrency seem useful.

**Comment by altayince** [comment]
I asked for help from my colleagues, whose job is to implementing an actual trade platform. They suggested Bitfinex API, which is also included in Cryptocurrency section in the link @irem-ustunboyacioglu  suggested. I think we can have a look at Bitfinex API.
