### ISSUE TITLE
Implement Authentication Mechanism

### ISSUE THREAD

**Issue by ufukyilmaz** [bounswe/bounswe2019group1#80]
Implement an authentication mechanism for identifying users and provide different access rights and content depending on their id. In order to do that, the session control will be provided.

**Comment by ufukyilmaz** [comment]
I think, the content of [this medium article](https://medium.com/createdd-notes/starting-with-authentication-a-tutorial-with-node-js-and-mongodb-25d524ca0359)  is enough for us to provide this mechanism.

**Comment by emirhansarac29** [comment]
This authentication will be postponed for future goals
